server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: http://192.168.186.128:9200
  rabbitmq:
    host: 192.168.186.128
    virtual-host: /feige
    username: feige
    password: feige
