server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
auth:
  jwt:
    publicKeyPath: D:\\software\\ideal\\project-0615\\tmp\\rsa.pub
    privateKeyPath: D:\\software\\ideal\\project-0615\\tmp\\rsa.pri
    expire: 180  #\u5355\u4F4D\u662F\u5206\u949F
    cookieName: GMALL_TOKEN
    secret: 2125412@!**..12ADjihghn